version: '3.8'

services:
  flask-proxy:
    image: python:3.11-slim
    container_name: flask-proxy
    working_dir: /app
    command: sh -c "
      pip install --no-cache-dir Flask Flask-BasicAuth requests &&
      flask run --host=0.0.0.0 --port=5000"
    ports:
      - "5000:5000"
    volumes:
      - ./micro_proxy.py:/app/micro_proxy.py
      - ./data.json:/app/data.json
    environment:
      - FLASK_APP=micro_proxy.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - FLASK_ENV=development         # <-- enables debug mode
      - FLASK_DEBUG=1
